import Converter from '@/components/tools/Converter/Converter';
import PageLayout from '@/components/ui/PageLayout/PageLayout';
import PageMeta from '@/components/content/PageMeta';
import PageTitle from '@/components/content/PageTitle';
import Paragraph from '@/components/ui/Paragraph/Paragraph';
import Section from '@/components/ui/Section/Section';
import SectionHeader from '@/components/ui/SectionHeader/SectionHeader';

export default function ConverterPage() {
	return (
		<>
			<PageMeta pageTitle='Tools - Online Converter' />
			<PageLayout>
				<PageTitle />
				<Section>
					<SectionHeader>Converter</SectionHeader>
					<Paragraph>
						The converter is a tool that creates an XML file and an image from a
						series of drop_block() function string. The resulting XML file provides
						a structured representation of the functions while the image shows
						the visual representation of the functions. It is recommended to use
						the converter on a desktop device to ensure optimal usage and
						accurate generation of output files.
					</Paragraph>
					<Paragraph>
						<span className='red'>
							Please note that the image generated by this tool is intended for
							illustrative purposes only and will not be used for evaluation.
							For the actual evaluation tool, we recommend checking out the{' '}
							<a href='https://github.com/chatgpt4pcg/modified-science-birds'>
								modified version of Science Birds.
							</a>
						</span>
					</Paragraph>
					<Converter />
				</Section>
			</PageLayout>
		</>
	);
}
