import Converter from '@/components/Converter/Converter';
import Head from 'next/head';
import PageHeader from '@/components/PageHeader/PageHeader';
import PageLayout from '@/components/PageLayout/PageLayout';
import PageSubHeader from '@/components/PageSubHeader/PageSubHeader';
import Paragraph from '@/components/Paragraph/Paragraph';
import Section from '@/components/Section/Section';
import SectionHeader from '@/components/SectionHeader/SectionHeader';

export default function XML() {
	return (
		<>
			<Head>
				<title>
					The 1st ChatGPT4PCG Competition: Character-like Level Generation for
					Science Birds
				</title>
				<meta
					name='description'
					content='The ChatGPT4PCG Competition invites participants to use ChatGPT to generate stable levels for Science Birds resembling English characters. Participants must submit a prompt and instructions, and the generated levels will undergo testing for stability and similarity using an OCR model, offering a chance to showcase prompt engineering skills and push the boundaries of natural language processing and procedural content generation.'
				/>
				<meta name='viewport' content='width=device-width, initial-scale=1' />
			</Head>
			<PageLayout>
				<PageSubHeader>The 1st ChatGPT4PCG Competition</PageSubHeader>
				<PageHeader>
					Character-like Level Generation for Science Birds
				</PageHeader>
				<Section>
					<SectionHeader>Converter</SectionHeader>
					<Paragraph>
						The converter is a tool that creates an XML file and image from a
						series of ab_drop() function string. The resulting XML file provides
						a structured representation of the functions while the image shows
						the visual representation of the functions. It is recommended to use
						the converter on a desktop device to ensure optimal usage and
						accurate generation of output files.
					</Paragraph>
					<Paragraph>
						<span className='red'>
							Please note that the image generated by this tool is intended for
							illustrative purposes only and will not be used for evaluation.
							For the actual evaluation tool, we recommend checking out the{' '}
							<a href='https://github.com/chatgpt4pcg/modified-science-birds'>
								modified version of Science Birds.
							</a>
						</span>
					</Paragraph>
					<Converter />
				</Section>
			</PageLayout>
		</>
	);
}
