import Divider from '@/components/ui/Divider/Divider';
import Link from 'next/link';
import PageLayout from '@/components/ui/PageLayout/PageLayout';
import PageMeta from '@/components/content/PageMeta';
import PageTitle from '@/components/content/PageTitle';
import Paragraph from '@/components/ui/Paragraph/Paragraph';
import Section from '@/components/ui/Section/Section';
import SectionHeader from '@/components/ui/SectionHeader/SectionHeader';
import SectionSubHeader from '@/components/ui/SectionSubHeader/SectionSubHeader';
import SectionSubSubHeader from '@/components/ui/SectionSubSubHeader/SectionSubSubHeader';

export default function ResourcesPage() {
	return (
		<>
			<PageMeta pageTitle='Resources' />
			<PageLayout>
				<PageTitle />
				<Section>
					<SectionHeader id='examples'>
						Prompt Engineering Examples
					</SectionHeader>
					<Paragraph>
						We provide a few example programs implemented using various prompt
						engineering techniques. These examples are offered to assist you in
						getting started with the competition. You can utilize these examples
						as a foundation to develop your own advanced prompt engineering
						techniques. The examples are accessible in a GitHub repository,
						which you can find{' '}
						<a href='https://github.com/chatgpt4pcg/pe-examples'>here</a>.
					</Paragraph>
				</Section>
				<Section>
					<SectionHeader id='tools'>Tools</SectionHeader>
					<SectionSubHeader id='chatgpt'>ChatGPT</SectionSubHeader>
					<ol>
						<li>
							Open your preferred web browser (such as Chrome, Firefox, or
							Safari).
						</li>
						<li>
							Navigate to the OpenAI website at{' '}
							<a href='https://chat.openai.com/chat'>
								https://chat.openai.com/chat
							</a>
						</li>
						<li>Start interact with the model.</li>
					</ol>
					<Divider />
					<SectionSubHeader id='science-birds-evaluator'>
						Science Birds Evaluator
					</SectionSubHeader>
					<Paragraph>
						This is a modified version of{' '}
						<a href='https://github.com/lucasnfe/science-birds'>
							Science Birds
						</a>{' '}
						that supports blocks used in the competition. It provides a feature
						that evaluates the stability of a particular level and generates an
						image used for the similarity checking script.
					</Paragraph>
					<Paragraph>
						You can download this version of Science Birds from{' '}
						<a href='https://github.com/chatgpt4pcg/modified-science-birds'>
							https://github.com/chatgpt4pcg/modified-science-birds
						</a>
						.
					</Paragraph>
					<SectionSubSubHeader id='sbe-installation'>
						Installation Instruction
					</SectionSubSubHeader>
					<ol>
						<li>
							Download <a href='https://unity.com/download'>Unity Hub</a>
						</li>
						<li>Open a project in Unity Hub</li>
						<li>Download the required version of Unity (if needed)</li>
						<li>Open the project in Unity</li>
					</ol>
					<Paragraph>
						For further installation steps, please refer to the{' '}
						<a href='https://github.com/lucasnfe/science-birds'>
							Science Birds
						</a>{' '}
						repository.
					</Paragraph>
					<Divider />
					<SectionSubHeader id='online-converter'>
						Online Converter
					</SectionSubHeader>
					<Paragraph>
						The converter is a tool that creates an XML file and an image from a
						series of <code>drop_block()</code> function string. The resulting
						XML file provides a structured representation of the functions while
						an image shows the visual representation of the functions. It is
						recommended to use the converter on a desktop device to ensure
						optimal usage and accurate generation of output files.
					</Paragraph>
					<ol>
						<li>
							Visit our online converter at{' '}
							<Link href='/tools/converter'>
								https://chatgpt4pcg.github.io/tools/converter
							</Link>
						</li>
						<li>
							Paste the text into the first input box, ensuring that it is in
							the correct format
						</li>
						<li>Click the &quot;Convert&quot; button.</li>
						<li>
							You can either copy or download the XML result and test it in
							Science Birds. To download the image, click the &quot;Download
							image&quot; button
						</li>
					</ol>
					<Paragraph>
						Note that the XML file must be placed in the{' '}
						<code>Assets/StreamingAssets/Levels</code> folder.
					</Paragraph>
					<span className='red'>
						Please note that the image generated by this online tool is intended
						for illustrative purposes only and will not be used for evaluation.
						For the actual evaluation tool, we recommend checking out the{' '}
						<a href='https://github.com/chatgpt4pcg/modified-science-birds'>
							modified version of Science Birds.
						</a>
					</span>
					<Divider />
					<SectionSubHeader id='online-code-extractor'>
						Online Code Extractor
					</SectionSubHeader>
					<Paragraph>
						The online code extractor extracts a code block from ChatGPT API
						responses, demonstrating the same algorithm used in the{' '}
						<a href='https://github.com/chatgpt4pcg/code-extraction-script'>
							code extraction script
						</a>
						.
					</Paragraph>
					<Paragraph>
						Visit our online code extractor at{' '}
						<Link href='/tools/code'>
							https://chatgpt4pcg.github.io/tools/code
						</Link>
						.
					</Paragraph>
					<Divider />
					<SectionSubHeader id='online-letter-classifier'>
						Online Letter Classifier
					</SectionSubHeader>
					<Paragraph>
						<span className='red'>
							Please note that the Online Letter Classifier embed in the tool
							page is also available at{' '}
							<a href='https://huggingface.co/spaces/pittawat/vit-base-uppercase-english-characters'>
								Hugging Face Spaces
							</a>{' '}
							and only shows the top five predicted classes with associated
							percentage. For the full version of the model, please use the{' '}
							<a href='https://github.com/chatgpt4pcg/similarity-checking-script'>
								similarity checking script
							</a>
							. This model was a fine-tuned version of{' '}
							<a href='https://huggingface.co/google/vit-base-patch16-224-in21k'>
								Vision Transformer (ViT)
							</a>{' '}
							trained on{' '}
							<a href='https://huggingface.co/datasets/pittawat/uppercase-english-characters'>
								this dataset
							</a>
							. More information on the dataset is also available on the same
							page.
						</span>
					</Paragraph>
					<Paragraph>
						Visit our online Letter Classifier at{' '}
						<Link href='/tools/classifier'>
							https://chatgpt4pcg.github.io/tools/classifier
						</Link>
						.
					</Paragraph>
					<Divider />
					<SectionSubHeader id='offline-scripts-packgaes'>
						Offline Scripts and Packages
					</SectionSubHeader>
					<Paragraph>
						Code extraction script -{' '}
						<a href='https://github.com/chatgpt4pcg/code-extraction-script'>
							https://github.com/chatgpt4pcg/code-extraction-script
						</a>
					</Paragraph>
					<Paragraph>
						Text-to-XML conversion script -{' '}
						<a href='https://github.com/chatgpt4pcg/text-to-xml-converter-script'>
							https://github.com/chatgpt4pcg/text-to-xml-converter-script
						</a>
					</Paragraph>
					<Paragraph>
						Similarity checking script -{' '}
						<a href='https://github.com/chatgpt4pcg/similarity-checking-script'>
							https://github.com/chatgpt4pcg/similarity-checking-script
						</a>
					</Paragraph>
					<Paragraph>
						Diversity checking script -{' '}
						<a href='https://github.com/chatgpt4pcg/diversity-checking-script'>
							https://github.com/chatgpt4pcg/diversity-checking-script
						</a>
					</Paragraph>
					<Paragraph>
						Scoring and ranking script -{' '}
						<a href='https://github.com/chatgpt4pcg/scoring-and-ranking-script'>
							https://github.com/chatgpt4pcg/scoring-and-ranking-script
						</a>
					</Paragraph>
					<Paragraph>
						<code>chatgpt4pcg</code> npm package -{' '}
						<a href='https://github.com/chatgpt4pcg/chatgpt4pcg'>
							https://github.com/chatgpt4pcg/chatgpt4pcg
						</a>
					</Paragraph>
					<Paragraph>
						<code>chatgpt4pcg</code> Python package -{' '}
						<a href='https://github.com/chatgpt4pcg/chatgpt4pcg-python'>
							https://github.com/chatgpt4pcg/chatgpt4pcg-python
						</a>
					</Paragraph>
				</Section>
			</PageLayout>
		</>
	);
}
